// SPDX-License-Identifier: Apache-2.0
/**
 * gsengai quickstart — from zero to a persisted, hash-only, tamper-evident evidence
 * record. Run from the repo root with `pnpm quickstart`.
 *
 * Keyless by default: a built-in mock OpenAI-shaped client is used and nothing
 * touches the network. Set OPENAI_API_KEY to run the same flow against the real
 * OpenAI API (optional; override the model with A50C_QUICKSTART_MODEL).
 */
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createEvidenceStore } from "@gsengai/core";
import { withEvidence } from "@gsengai/openai";

const outDir = join(dirname(fileURLToPath(import.meta.url)), ".out");
mkdirSync(outDir, { recursive: true });
const dbPath = join(outDir, "evidence.db");

const QUESTION = "In one sentence: why do transparency obligations for AI-generated content exist?";
const MOCK_ANSWER =
  "Transparency obligations exist so that people can recognize when content was " +
  "generated by a machine rather than a person.";

/** Verbatim limits & disclaimer block (PRD §9). */
const DISCLAIMER = `
What this does NOT do

- It does not make you compliant. It supports compliance with EU AI Act Article 50 and California SB 942; compliance depends on your system, your deployment context, and your processes.
- It does not embed imperceptible watermarks (MVP). It implements the signed-metadata and logging/fingerprinting layers of a multi-layer marking strategy.
- It cannot prevent downstream metadata stripping — manifests can be removed by re-encoding, screenshots, or platform uploads. That is exactly why the logging layer exists.
- It does not detect third-party AI content.
- It is not legal advice. Consult qualified counsel about your obligations.
`;

interface ChatClient {
  chat: {
    completions: {
      create: (params: {
        model: string;
        messages: Array<{ role: "user"; content: string }>;
      }) => Promise<unknown>;
    };
  };
}

function makeMockClient(): ChatClient {
  return {
    chat: {
      completions: {
        create: async (params) => ({
          id: "chatcmpl-quickstart-mock",
          object: "chat.completion",
          model: params.model,
          choices: [
            {
              index: 0,
              message: { role: "assistant", content: MOCK_ANSWER },
              finish_reason: "stop",
            },
          ],
        }),
      },
    },
  };
}

async function makeClient(): Promise<{ client: ChatClient; mode: string; model: string }> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (apiKey) {
    try {
      const { default: OpenAI } = await import("openai");
      return {
        client: new OpenAI({ apiKey }) as unknown as ChatClient,
        mode: "live OpenAI API (OPENAI_API_KEY detected)",
        model: process.env.A50C_QUICKSTART_MODEL ?? "gpt-4o-mini",
      };
    } catch (err) {
      console.warn(
        "[quickstart] OPENAI_API_KEY is set but the openai package could not be loaded; using the mock client instead.",
        err,
      );
    }
  }
  return {
    client: makeMockClient(),
    mode: "built-in mock client (keyless — zero network access)",
    model: "mock-gpt",
  };
}

async function main(): Promise<void> {
  const { client, mode, model } = await makeClient();
  const store = createEvidenceStore({ path: dbPath });

  // One line to add evidence logging — the client is used exactly as before.
  const wrapped = withEvidence(client, { store, systemId: "quickstart-demo" });

  console.log(`Mode: ${mode}\n`);
  const response = (await wrapped.chat.completions.create({
    model,
    messages: [{ role: "user", content: QUESTION }],
  })) as { choices: Array<{ message: { content: string | null } }> };

  const text = response.choices[0]?.message.content ?? "";
  console.log(`Model output:\n  ${text}\n`);

  // The store is append-only across runs; .at(-1) shows the record from this run.
  const record = store.findByText(text).at(-1);
  console.log("Persisted evidence record (hashes and metadata only — raw text never persists):");
  console.log(JSON.stringify(record, null, 2));

  const chain = store.verifyChain();
  console.log(`\nTamper-evident hash chain: ok=${chain.ok}, records checked=${chain.checked}`);

  const exported = await store.exportJsonl(join(outDir, "evidence-export.jsonl"));
  console.log(`JSONL audit export: ${exported.records} record(s) -> ${exported.path}`);
  console.log(`Evidence database: ${dbPath}`);
  console.log(DISCLAIMER);

  store.close();
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
