// SPDX-License-Identifier: Apache-2.0
// Rendered sample of the Markdown audit report: built
// live on each request from sample data via the real `buildAuditReport`.
import Link from "next/link";
import { BRAND } from "../../lib/brand";
import { renderSampleReport } from "../../lib/report-sample";

export const dynamic = "force-dynamic";

export default async function AuditReportSamplePage() {
  const reportHtml = await renderSampleReport();
  return (
    <main className="wrap report-page">
      <header className="masthead">
        <span className="wordmark">{BRAND}</span>
        <span className="masthead-role">audit report sample</span>
      </header>
      <p className="report-note card-sub" style={{ color: "var(--muted)" }}>
        This is the human-readable audit report produced by <code>buildAuditReport</code> (also
        available via the <code>gsengai-audit</code> CLI), rendered from its Markdown source — the
        artifact a team hands its counsel or a supervisory authority. It was generated live from
        sample data when you loaded this page; the same export runs against any real evidence store.
        Markdown renders anywhere — for PDF, use any Markdown-to-PDF step (e.g. pandoc).{" "}
        <Link className="back-link" href="/">
          ← Back to the demo
        </Link>
      </p>
      {/* Report HTML is generated by our own renderer from sample data — no user input. */}
      {/* biome-ignore lint/security/noDangerouslySetInnerHtml: trusted, self-generated markdown */}
      <article className="report" dangerouslySetInnerHTML={{ __html: reportHtml }} />
    </main>
  );
}
